spring:
  rabbitmq:
    password: admin
    port: 5672
    host: localhost
    username: admin

rabbitmq:
  binding:
    routing:
      key: order-routing-key
    email:
      routing:
        key: email-routing-key
  queue:
    order:
      name: order-queue
    email:
      name: email-queue
  exchange:
    name: order-exchange

server:
  port: 8080